# Generated by Django 3.2.4 on 2021-06-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxdriveapp', '0003_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='desc',
        ),
        migrations.AlterField(
            model_name='document',
            name='file_field',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
