# Generated by Django 3.2.4 on 2021-06-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxdriveapp', '0004_auto_20210613_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='cur_user',
        ),
    ]
