# Generated by Django 3.2.4 on 2021-06-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxdriveusersreg', '0001_initial'),
        ('boxdriveapp', '0006_alter_document_cur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cur_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxdriveusersreg.profile'),
        ),
    ]
